services:
  db:
    image: postgres:16
    container_name: localchat-db
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - .env
    restart: on-failure
