version: "3"

services:
  db:
    image: postgres:16
    container_name: localchat-db
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file:
      - .env
    restart: unless-stopped
