version: "3"

networks:
  localchat:
    driver: bridge

volumes:
  postgre:
    driver: local
  minio:
    driver: local

services:
  db:
    image: postgres:16
    container_name: localchat-db
    ports:
      - 5432:5432
    volumes:
      - postgre:/var/lib/postgresql/data
    env_file:
      - .env
    restart: unless-stopped

  minio:
    image: "bitnami/minio:latest"
    container_name: localchat-minio
    ports:
      - 9000:9000
      - 9001:9001 # The admin console
    env_file:
      - .env
    volumes:
      - minio:/bitnami/minio/data
    networks:
      - localchat
    restart: unless-stopped

  # backend:
  #   build:
  #     dockerfile: ./Dockerfile.backend
  #   container_name: localchat-backend
  #   ports:
  #     - 8000:8000
  #   env_file:
  #     - .env
  #   restart: unless-stopped
  #   depends_on:
  #     - db
  #     - minio
