FROM golang:1.21.4

RUN mkdir /app
WORKDIR /app

ENV GO111MODULE=on 
ENV GOPRIVATE=github.com/FKuiv/LocalChat

COPY .env .
COPY go.mod .
COPY go.sum .
COPY main.go .
COPY pkg/ ./pkg

RUN go mod tidy

RUN go build -o /localchat

EXPOSE 8000

CMD ["/localchat"]