FROM golang:1.21.4

WORKDIR /localchat

COPY go.mod .
COPY go.sum .
COPY main.go .
RUN export GOPRIVATE=github.com/FKuiv/*
RUN go mod download
RUN go mod tidy

COPY ./pkg/**/* .

RUN go build -o /localchat

EXPOSE 8000

CMD ["/localchat"]