version: "3"

services:
  db:
    image: postgres:16
    container_name: localchat-db
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file:
      - .env
    restart: unless-stopped

  backend:
    build:
      dockerfile: ./Dockerfile.backend
    container_name: localchat-backend
    ports:
      - 8000:8000
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db
