version: "3"

networks:
  localchat:
    driver: bridge

services:
  db:
    image: postgres:16
    container_name: localchat-db
    ports:
      - 5432:5432
    volumes:
      - ./data/postgre:/var/lib/postgresql/data
    env_file:
      - .env
    restart: unless-stopped

  minio:
    image: "bitnami/minio:latest"
    ports:
      - 9000:9000
    env_file:
      - .env
    volumes:
      - ./data/minio:/bitnami/minio/data
    networks:
      - localchat

  # backend:
  #   build:
  #     dockerfile: ./Dockerfile.backend
  #   container_name: localchat-backend
  #   ports:
  #     - 8000:8000
  #   env_file:
  #     - .env
  #   restart: unless-stopped
  #   depends_on:
  #     - db
